#pragma config(Sensor, in1,    angle,               sensorPotentiometer)
#pragma config(Sensor, in2,    lineFollowerRIGHT,   sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCENTER,  sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerLEFT,    sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerSIDE,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  conveyorFront,       sensorTouch)
#pragma config(Sensor, dgtl2,  conveyorBack,        sensorTouch)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorRotation)
#pragma config(Sensor, dgtl4,  rightEncoder,        sensorRotation)
#pragma config(Motor,  port1,           LeftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port2,           Armleft1Motor, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           Armleft2Motor, tmotorNormal, openLoop)
#pragma config(Motor,  port4,           basket1Motor,  tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           basket2Motor,  tmotorNormal, openLoop)
#pragma config(Motor,  port6,           conveyor1Motor, tmotorNormal, openLoop)
#pragma config(Motor,  port7,           conveyor2Motor, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          RightMotor,    tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//=============================================| DRIVE |==============================================
int leftE = SensorValue(leftEncoder);
int rightE = SensorValue(rightEncoder);


task line()
{
  int line = SensorValue(lineFollowerCENTER);

  // RIGHT sensor sees dark:
  if(SensorValue(lineFollowerRIGHT) < 1500 )
  {
    // counter-steer right:
    motor[LeftMotor]  = 40;
    motor[RightMotor] = 80;
  }
  // CENTER sensor sees dark:
  if(SensorValue(lineFollowerCENTER) < 1500)
  {
    // go straight
    motor[LeftMotor]  = 80;
    motor[RightMotor] = 80;
  }
  // LEFT sensor sees dark:
  if(SensorValue(lineFollowerLEFT) < 1500)
  {
    // counter-steer left:
    motor[LeftMotor]  = 80;
    motor[RightMotor] = 40;
  }
}

task autonmous()
{
  int side = SensorValue(lineFollowerSIDE);
  while(side > 1000)
  {
    StartTask(line);
    side = SensorValue(lineFollowerSIDE);
  }

  SensorValue(leftEncoder) = 0;
  SensorValue(rightEncoder) = 0;

  leftE = SensorValue(leftEncoder);
  rightE = SensorValue(rightEncoder);

  while(leftE < 80 && rightE < 80)
  {
    motor[LeftMotor] = 80;
    motor[RightMotor] = -80;
    leftE = SensorValue(leftEncoder);
    rightE = SensorValue(rightEncoder);
  }

}

task drive()
{
  motor[LeftMotor] = vexRT[Ch3];
  motor[RightMotor] = vexRT[Ch2];
}



task conveyor_belt()
{

  if(vexRT[Btn5U] == 1)
  {
    motor[conveyor1Motor] = 127;
    motor[conveyor2Motor] = 127;
    StartTask(drive);
    if(SensorValue(conveyorFront) == 0)
    {
      motor[basket1Motor] = 127;
      motor[basket2Motor] = 127;


    }
    else
    {
      motor[basket1Motor] = 0;
      motor[basket2Motor] = 0;

    }
  }
  else if(vexRT[Btn5U] == 0)
  {
    motor[conveyor1Motor] = 0;
    motor[conveyor2Motor] = 0;
    motor[basket1Motor] = 0;
    motor[basket2Motor] = 0;
  }



  if(vexRT[Btn5D] == 1)
  {
    motor[conveyor1Motor] = -127;
    motor[conveyor2Motor] = -127;
    StartTask(drive);
    if(SensorValue(conveyorBack) == 0)
    {
      motor[basket1Motor] = -127;
      motor[basket2Motor] = -127;


    }
    else
    {
      motor[basket1Motor] = 0;
      motor[basket2Motor] = 0;
    }

  }
  else if(vexRT[Btn5D] == 0)
  {
    motor[conveyor1Motor] = 0;
    motor[conveyor2Motor] = 0;
    motor[basket1Motor] = 0;
    motor[basket2Motor] = 0;
  }


}

task essentials()
{
  StartTask(drive);
  StartTask(conveyor_belt);
}

void lift(int target)
{
  int actual = SensorValue(angle);
  if(target < 2000)
    target = 2000;
  if(actual < target)
  {
    while(actual < target)
    {
      motor[Armleft1Motor] = 127;
      motor[Armleft2Motor] = 127;
      actual = SensorValue(angle);
      StartTask(essentials);
    }

    motor[Armleft1Motor] = 20;
    motor[Armleft2Motor] = 20;
  }
  else if(actual > target && target > 2000)
  {
    while(actual > target)
    {
      motor[Armleft1Motor] = -80;
      motor[Armleft2Motor] = -80;
      actual = SensorValue(angle);
      StartTask(essentials);
    }
    motor[Armleft1Motor] = 20;
    motor[Armleft2Motor] = 20;
  }
  else if(target == 2000)
  {
    while(actual > target)
    {
      motor[Armleft1Motor] = -80;
      motor[Armleft2Motor] = -80;
      actual = SensorValue(angle);
      StartTask(essentials);
    }
    motor[Armleft1Motor] = 0;
    motor[Armleft2Motor] = 0;
  }
}





//====================================================================================================


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

  int cycle = 0;
  while(true)
  {
    leftE = SensorValue(leftEncoder);
    rightE = SensorValue(rightEncoder);
    StartTask(drive);
    StartTask(conveyor_belt);
    // int arm = SensorValue(angle);
    if(vexRT[Btn8U] == 1)
      StartTask(autonmous);


    if(vexRT[Btn7U] == 1)
    {

      cycle++;
      if(cycle == 4)
        cycle = 0;
    }
    if(vexRT[Btn7D] == 1)
      // cycle = 0;
    cycle--;

    if(cycle == -1)
      cycle = 0;

    switch(cycle)
    {
    case 0:
      lift(2000);
      break;

    case 1:
      lift(2600);
      break;

    case 2:
      lift(3000);
      break;

    case 3:
      lift(3500);
      break;
    }


    // switch(cycle)
    // {
    // case 0:
    // while(arm > 2000)
    // {

    // motor[Armleft1Motor] = -80;
    // motor[Armleft2Motor] = -80;
    // arm = SensorValue(angle);
    // StartTask(essentials);
    // }
    // motor[Armleft1Motor] = 0;
    // motor[Armleft2Motor] = 0;
    // break;
    // case 1:
    // while(arm < 2600)
    // {
    // motor[Armleft1Motor] = 127;
    // motor[Armleft2Motor] = 127;
    // arm = SensorValue(angle);
    // StartTask(essentials);
    // }
    // motor[Armleft1Motor] = 20;
    // motor[Armleft2Motor] = 20;
    // break;
    // case 2:
    // while(arm < 3000)
    // {
    // motor[Armleft1Motor] = 127;
    // motor[Armleft2Motor] = 127;
    // arm = SensorValue(angle);
    // StartTask(essentials);
    // }
    // motor[Armleft1Motor] = 20;
    // motor[Armleft2Motor] = 20;
    // break;
    // case 3:
    // while(arm < 3500)
    // {
    // motor[Armleft1Motor] = 127;
    // motor[Armleft2Motor] = 127;
    // arm = SensorValue(angle);
    // StartTask(essentials);
    // }
    // motor[Armleft1Motor] = 20;
    // motor[Armleft2Motor] = 20;
    // break;
    // }

  }
}







//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
