#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftPneumatics, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rightPneumatics, sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftLift1,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftLift2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftRoll,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftDriveF,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftDriveB,    tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           rightDriveB,   tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           rightDriveF,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           rightRoll,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightLift2,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightLift1,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int armState = 0; // 0 - 2, 0 = neutral, 1 = lift, 2 = down
int strafeSpeed = 127;
int armSpeed[] = {10, 127, -60}; //0 = neutral, 1 = lift, 2 = down
int intakeSpeed = 127;
bool strafe = false;
bool driveEnable = true;


void setDrive(int left, int right);
void setDrive(int strafe);
void runExpansion();
void setArm(int lift);
void setIntake(int speed);
void brake();


task drive();
task arm();
task buttons();
task pneumatics();



task drive(){
	if(driveEnable) setDrive(vexRT[Ch3], vexRT[Ch2]);
}

task arm(){
	setArm(armSpeed[armState]);
}

task buttons(){
	if(strafe){
		if(vexRT[Btn8L] == 1){
			driveEnable = false;
			setDrive(strafeSpeed*-1);
		}
		else if(vexRT[Btn8R] == 1){
			driveEnable = false;
			setDrive(strafeSpeed);
		}
		else if(vexRT[Btn8U] == 1){
			driveEnable = false;
			runExpansion();
		}
		else driveEnable = true;
	}
	if(vexRT[Btn7D] == 1) strafe = true;
	if(vexRT[Btn8D] == 1) strafe = false;

	if(vexRT[Btn5U] == 1) armState = 1;
	else if(vexRT[Btn5D] == 1) armState = 2;
	else armState = 0;

	if(vexRT[Btn6U] == 1) setIntake(intakeSpeed);
	else if(vexRT[Btn6D] == 1) setIntake(intakeSpeed*-1);
	else setIntake(0);
}

task pneumatics(){
	if(strafe){
		SensorValue(leftPneumatics) = 1;
		SensorValue(rightPneumatics) = 1;
	}
	else{
		SensorValue(leftPneumatics) = 0;
		SensorValue(rightPneumatics) = 0;
	}
}

void setDrive(int left, int right){
	motor[leftDriveF] = left;
	motor[leftDriveB] = left;
	motor[rightDriveF] = right;
	motor[rightDriveB] = right;
}

void setDrive(int strafe){
	motor[leftDriveF] = strafe * -1;
	motor[leftDriveB] = strafe;
	motor[rightDriveF] = strafe;
	motor[rightDriveB] = strafe * -1;
}

void runExpansion(){
	strafe = true;
	setDrive(127,127);
	wait1Msec(250);
	setDrive(-127,-127);
	wait1Msec(250);
	motor[leftDriveF] = 127;
	motor[leftDriveB] = -127;
	motor[rightDriveF] = 127;
	motor[rightDriveB] = -127;
	wait1Msec(250);
	brake();
}

void setArm(int lift){
	motor[leftLift1] = lift;
	motor[leftLift2] = lift;
	motor[rightLift1] = lift;
	motor[rightLift2] = lift;
}

void setIntake(int speed){
	motor[leftRoll] = speed;
	motor[rightRoll] = speed;
}

void brake(){
	setDrive(0, 0);
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
runExpansion();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	while(true){
		StartTask(drive);
		StartTask(arm);
		StartTask(buttons);
		StartTask(pneumatics);
	}

}
