#pragma config(Sensor, dgtl1,  leftPneumatics, sensorDigitalIn)
#pragma config(Sensor, dgtl2,  rightPneumatics, sensorDigitalIn)
#pragma config(Motor,  port1,           leftDriveF,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftDriveB,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftLift1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftLift2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           leftRoll,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightDriveF,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightDriveB,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           rightLift1,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightLift2,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightRoll,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int armState = 0; // 0 - 2, 0 = neutral, 1 = lift, 2 = down
int strafeSpeed = 100;
int armSpeed[] = {5, 127, -60}; //0 = neutral, 1 = lift, 2 = down
int intakeSpeed = 127;
bool strafe = false;
bool driveEnable = true;


void setDrive(int left, int right);
void setDrive(int strafe);
void setArm(int lift);
void setIntake(int speed);
void brake();
void autonomous();

task drive();
task arm();
task buttons();
task pneumatics();

task main(){
	while(true){
		StartTask(drive);
		StartTask(arm);
		StartTask(buttons);
		StartTask(pneumatics);
	}
}

task drive(){
	if(driveEnable) setDrive(vexRT[Ch3], vexRT[Ch2]);
	else brake();
}

task arm(){
	setArm(armSpeed[armState]);
}

task buttons(){
	if(strafe){
		if(vexRT[Btn8L] == 1){
			driveEnable = false;
			setDrive(strafeSpeed * -1);
		}
		else if(vexRT[Btn8R] == 1){
			setDrive(strafeSpeed);
			driveEnable = false;
		}
		else driveEnable = true;
	}
	if(vexRT[Btn7D] == 1) strafe = true;
	else if(vexRT[Btn8D] == 1) strafe = false;

	if(vexRT[Btn5U] == 1) armState = 1;
	else if(vexRT[Btn5D] == 1) armState = 2;
	else armState = 0;

	if(vexRT[Btn6U] == 1) setIntake(intakeSpeed);
	else if(vexRT[Btn6D] == 1) setIntake(intakeSpeed * -1);
	else setIntake(0);
}

task pneumatics(){
	if(strafe){
		SensorValue(leftPneumatics) = 1;
		SensorValue(rightPneumatics) = 1;
	}
	else{
		SensorValue(leftPneumatics) = 0;
		SensorValue(rightPneumatics) = 0;
	}
}

void setDrive(int left, int right){
	motor[leftDriveF] = left;
	motor[leftDriveB] = left;
	motor[rightDriveF] = right;
	motor[rightDriveB] = right;
}

void setDrive(int strafe){
	motor[leftDriveF] = strafe;
	motor[leftDriveB] = strafe * -1;
	motor[rightDriveF] = strafe * -1;
	motor[rightDriveB] = strafe;
}

void setArm(int lift){
	motor[leftLift1] = lift;
	motor[leftLift2] = lift;
	motor[rightLift1] = lift;
	motor[rightLift2] = lift;
}

void setIntake(int speed){
	motor[leftRoll] = speed;
	motor[rightRoll] = speed;
}

void brake(){
	setDrive(0, 0);
}

void autonomous(){

}
